In [17]:
import numpy as np 
a = np.array([[2,3,1],[-1,1,0],[1,2,-1]])
b = np.array([[1,2,1],[0,1,2],[3,1,1]])
ab = a.dot(b)
ba = b.dot(a)
c = ab - ba
print(c)

[[ 4  1  9]
 [-2 -6  3]
 [-8 -9  2]]


In [18]:
a = np.array([[-1,0,2],[0,1,0],[1,2,-1]])
a_2 = np.linalg.matrix_power(a, 2)
print(a_2)

[[ 3  4 -4]
 [ 0  1  0]
 [-2  0  3]]


In [19]:
a = np.matrix('5 0 2 3; 4 1 5 3; 3 1 -1 2') 
b = np.matrix('6; -2; 7; 4') 
c = a.dot(b) 
print(c)

[[56]
 [69]
 [17]]


In [20]:
a = np.matrix('2 3 4; 1 0 6; 7 8 9') 
det = np.linalg.det(a)
print("Визначник = ", det.round(1))

Визначник =  35.0


In [24]:
a = np.matrix('1 2 3 4;-2 1 -4 3; 3 -4 -1 2; 4 3 -2 -1')
det = np.linalg.det(a)
print("Визначник = ", det.round(1))

Визначник =  900.0


In [26]:
a = np.array([[2,5,7],[6,3,4],[5,-2,-3]])
inv = np.linalg.inv(a)
print('Обернена матриця : ',"\n", inv)

Обернена матриця :  
 [[  1.  -1.   1.]
 [-38.  41. -34.]
 [ 27. -29.  24.]]


In [28]:
a = np.array([[1,2,3,4],[3,-1,2,5],[1,2,3,4],[1,3,4,5]])
rank_a = np.linalg.matrix_rank(a)
print(rank_a)

2


In [43]:
a = np.array([[1,2,3],[1,3,4],[2,-1,-1]])
b = np.array([[5],[6],[1]])
def kram(a,b):# метод Крамера
    det_a = np.linalg.det(a)
    if det_a != 0:
       a1 = np.matrix(a)
       a2 = np.matrix(a)
       a3 = np.matrix(a)
       a1[:, 0] = b
       a2[:, 1] = b
       a3[:, 2] = b
       x = np.linalg.det(a1)/det_a
       y =np.linalg.det(a2)/det_a
       z= np.linalg.det(a3)/det_a
       # print('Solving a system of linear algebraic equations by Cramer*s method')
       print('x=',x.round(1),'y=',y.round(1),'z=',z.round(1)) 
    else:
        print("Система немає розв'язків, оскільки визначник дорівнює 0 ")
    return(x,y,z)
kram(a,b)
print("Перевірка розв'язання : ","\n", np.linalg.solve(a,b).round(1))

x= 1.0 y= -1.0 z= 2.0
Перевірка розв'язання :  
 [[ 1.]
 [-1.]
 [ 2.]]


In [47]:
a = np.array([[1,2,3],[1,3,4],[2,-1,-1]])
b = np.array([[5],[6],[1]])
inv_a = np.linalg.inv(a)
x = inv_a.dot(b)
print('X=', x)
print("Перевірка розв'язання : ","\n", np.linalg.solve(a,b).round(1))

X= [[ 1.]
 [-1.]
 [ 2.]]
Перевірка розв'язання :  
 [[ 1.]
 [-1.]
 [ 2.]]


In [72]:
import random as rd
n = 3
m = 4
a = np.zeros((n, m), dtype=int)
for i in range(n): #наповнюємо матрицю випадковими числами від 1 до 20
    for j in range(m):
        a[i][j] = rd.randint(1, 20)

print(a)

for i in range(n): #обчислення середнього значення для кожного рядка
    suma_row = 0
    for j in range(m):
        suma_row += a[i][j]
    average_row = suma_row / m
    print(f"Середнє значення {i+1} рядка: {(average_row).round(1)}")

for j in range(m): #обчислення середнього значення для кожного стовпця
    suma_column = 0
    for i in range(n):
        suma_column += a[i][j]
    average_column = suma_column / n
    print(f"Середнє значення {j+1} стовпця: {(average_column).round(1)}")

[[ 2  8 17  9]
 [17 10 11  9]
 [ 9 13  7  2]]
Середнє значення 1 рядка: 9.0
Середнє значення 2 рядка: 11.8
Середнє значення 3 рядка: 7.8
Середнє значення 1 стовпця: 9.3
Середнє значення 2 стовпця: 10.3
Середнє значення 3 стовпця: 11.7
Середнє значення 4 стовпця: 6.7
